# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-09-20 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elephant', '0002_mapburglar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mapburglar',
        ),
    ]
