# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-09-20 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elephant', '0005_auto_20170920_1729'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='daanburglar',
            new_name='mapburglar',
        ),
    ]
