# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-09-20 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elephant', '0008_auto_20170920_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daanburglar',
            name='mapID',
        ),
        migrations.AlterField(
            model_name='daanburglar',
            name='id',
            field=models.IntegerField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
