# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-09-26 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elephant', '0015_daanfiredepart_daanpolice'),
    ]

    operations = [
        migrations.CreateModel(
            name='daanpets10000',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('mapUrl', models.CharField(max_length=60)),
                ('mapName', models.CharField(max_length=60)),
                ('mapAddress', models.CharField(max_length=60)),
                ('mapLat', models.CharField(max_length=20)),
                ('mapLng', models.CharField(max_length=20)),
                ('mapcityID', models.CharField(max_length=5)),
                ('mapLabel', models.CharField(max_length=5)),
                ('mapRent', models.CharField(max_length=10)),
                ('mapLandlord', models.CharField(max_length=60)),
                ('mapSpace', models.CharField(max_length=10)),
                ('mapPet', models.CharField(max_length=5)),
                ('mapSex', models.CharField(max_length=5)),
                ('mapCook', models.CharField(max_length=5)),
                ('mapAvgonfood', models.CharField(max_length=5)),
                ('mapSmoke', models.CharField(max_length=5)),
            ],
        ),
    ]
