# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-09-27 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elephant', '0018_tucheng3km10000_tucheng5km_tucheng5km10000'),
    ]

    operations = [
        migrations.CreateModel(
            name='daanfuneral',
            fields=[
                ('mapName', models.CharField(max_length=60)),
                ('mapLat', models.CharField(max_length=20)),
                ('mapLng', models.CharField(max_length=20)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('mapAddress', models.CharField(max_length=60)),
                ('mapcityID', models.CharField(max_length=20)),
            ],
        ),
    ]
